name: ysave
description: Sample app on how to get started with Supabase on Flutter.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bezier_chart: "^1.0.16"
  flutter:
    sdk: flutter

  flutter_dotenv: ^5.0.2
  flutter_sparkline: ^0.1.0
  font_awesome_flutter: ^8.8.1
  google_fonts: ^3.0.1
  image_picker: ^0.8.4
  supabase_flutter: ^0.2.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.3

flutter:
  uses-material-design: true

  assets:
    - .env
