name: ysave
description: Sample app on how to get started with Supabase on Flutter.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  barcode_scan2: ^4.2.1
  cupertino_icons: ^0.1.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_launcher_icons: ^0.10.0
  flutter_polyline_points: ^1.0.0
  flutter_sparkline: ^0.1.0
  flutter_svg: ^1.1.5
  font_awesome_flutter: ^10.2.1
  geolocator: ^9.0.2
  google_fonts: ^3.0.1
  google_maps_flutter: ^2.2.1
  google_maps_flutter_web: ^0.4.0+3
  http: ^0.13.5
  image_picker: ^0.8.4
  location: ^4.4.0
  otp_text_field: ^1.1.3
  path_provider: ^2.0.1
  qr_flutter: ^4.0.0
  supabase_flutter: ^0.2.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.3

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/Toll-Pay.png
    - assets/images/qr-code.png
    - assets/images/TollPay-logo.png
